### ISSUE TITLE
Support with demo

### ISSUE THREAD

**Issue by johnfelipe** [wpbrasil/gerador-de-certificados#1]
Hi please help me for try a demo

Tnks

**Comment by vmassuchetto** [comment]
Hi Felipe. Did you follow the README file? Are you getting any errors?

**Comment by johnfelipe** [comment]
Yes:

"A template certificate is pretty much a background image with proper locations to have a name and description inserted. They need to be located at img/bg-<certificate type>.png. The location of the name and description can be set in config.php throught the IMG_NAME_\* and IMG_DATA_\* constants."

cannot try

**Comment by johnfelipe** [comment]
Hi, please share me some help, tnks

**Comment by johnfelipe** [comment]
Hi, please help me with your app, tnks

**Comment by espellcaste** [comment]
I haven't understood your problem @johnfelipe, could you elaborate it?
