### ISSUE TITLE
Transformar em plugin

### ISSUE THREAD

**Issue by vmassuchetto** [wpbrasil/gerador-de-certificados#2]
Seguindo da discussão [aqui](http://participe.wp-brasil.org/2014/10/20/gerador-de-certificados/), penso que a transformação em plugin pode ser viabilizado como:
- Post type 'certificado', com todas as opções necessárias conforme o README do plugin (espaçamentos, fonte, tamanho de fonte, imagem de fundo, etc);
- Post type 'participante' com a taxonomia 'tipo de participante', com as opções necessárias para exibir o texto correto conforme cada tipo de participante (participante comum, palestrante, organizador).

**Comment by valeriosouza** [comment]
Seria bom ter um jeito de separar os cadastros por WordCamp, e só o administrador de cada WordCamp ter acesso a isso, já que temos como regra, cuidar dos emails de cada um.

**Comment by vmassuchetto** [comment]
Acho que as permissões padrões do WordPress devem ser capazes de administrar isso -- cadastrando os organizadores de WordCamps como autores, por exemplo.

**Comment by valeriosouza** [comment]
Mas cada autor ter acesso somente a sua lista de emails. Prevenir que possa vazar essa lista de emails.

**Comment by greguly** [comment]
Creio que as listas de emails devem ser disponiveis para qualquer organizador de WordCamps, afinal de contas são eventos da comunidade brasileira como um todo.

**Comment by rafaehlers** [comment]
Não viaja @greguly , WordCamps são regionais! Eu não darei a lista de Porto Alegre pra mandarem propaganda de outros estados, não foi isto o acordado com os participantes que me confiaram seus emails. Foi por este motivo que não aceitei negociar com UOLHost, queriam a lista de emails para fazer spam. NEVER!

**Comment by RafaelFunchal** [comment]
> Creio que as listas de emails devem ser disponiveis para qualquer organizador de WordCamps, afinal de contas são eventos da comunidade brasileira como um todo.

Discordo fortemente disso, @greguly . Se for seguir essa lógica, então todos os organizadores teriam acesso à todos os outros sites da rede wordcamp.org. Imagina que ~dá hora~ um WC pequeno com os dados do WCSF.

**Comment by valeriosouza** [comment]
Isso que eu disse. Sem falar que pode ter alguém com interesses errados, e vender essa lista pra alguma empresa x. No código de conduta isso é claro que não vai acontecer.

**Comment by leobaiano** [comment]
Se for para fazer como plugin e com a ideia de que este seja integrado a todos os sites de WordCamp não vamos precisar do post type participantes, podemos pegar com base nos inscritos no evento e gerar certificado apenas para os que tiverem a presença confirmada pelos organizadores do evento, o camptix já tem essa parada lá.

Já o post type certificados não precisaria daquelas opções que o @vmassuchetto falou, as configurações ficariam como opções do plugin.

O que penso é uma tela de opções subir a imagem de fundo, nem precisaria configurar tamanho de fonte, já pode deixar padrão. Então no final do evento o admin vai em "gerar certificados" e o plugin gera um por um, manda por e-mail e cria uma lista com os certificados enviados e a opção de salvar o arquivo do certificado dos participantes, assim se houver problemas pode salvar o certificado e mandar por e-mail.

**Comment by greguly** [comment]
@rafaehlers: Desculpe, não me expressei corretamente.

 Estar disponivel não é igual a ter a lista com os nomes e os emails. ;-)

Com certeza o MailPoet tem esta funcionalidade, onde alguém pode enviar mensagems sem saber a lista dos destinatários.

Concordo plenamente que os emails não devem ser compartilhados com entidades externas, apenas acho que seria legal outros organizadores de WordCamps terem acesso a uma forma de se comunicarem com quem frequenta os eventos. 

@rafaelfunchal Concordo contigo que os dados de cada WC são privados dos organizadores, como disse acima, não me expressei corretamente.

**Comment by danilodorgam** [comment]
Galera, acabou que não foi pra frente, esse código ainda é usado?

**Comment by claudiosanches** [comment]
Não, estamos usando isso hoje: https://github.com/wpbrasil/certificates-for-wordcamp
