### ISSUE TITLE
Gerar Verso Certificado

### ISSUE THREAD

**Issue by stazjacc** [wpbrasil/gerador-de-certificados#4]
Olá, 
gostaria de saber como poderia adaptar o código para poder gerar um certificado com frente e verso?

Obrigado!

**Comment by rodrigo-brito** [comment]
Boa tarde @stazjacc, recomendo você dar uma olhada no novo gerador de certificados, é bem mais prático e personalizável. https://github.com/wpbrasil/certificates-for-wordcamp

**Comment by rodrigo-brito** [comment]
Basicamente ele gera um PDF através de um modelo em HTML, se você gerar duas páginas pode imprimi-lo em frente everso.

**Comment by stazjacc** [comment]
Obrigado pelo feedback @rodrigo-brito. Valew!!!
